import Head from "next/head";
import Article from "../components/Article";

const Home = ({ articles }) => {
  return (
    <>
      <Head>
        <title>NextBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-white dark:bg-gray-900">
        <div className="py-8 px-4 mx-auto max-w-screen-xl lg:py-16 lg:px-6">
          <div className="mx-auto max-w-screen-sm text-center lg:mb-16 mb-8">
            <h2 className="mb-4 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">
              NextBlog
            </h2>
            <p className="font-light text-gray-500 sm:text-xl dark:text-gray-400">
              Using Strapi.js as a headless CMS.
            </p>
          </div>
          <div className="grid gap-8 lg:grid-cols-2">
            {articles?.data?.map((article) => {
              return <Article article={article} />;
            })}
          </div>
        </div>
      </section>
    </>
  );
};

export const getServerSideProps = async (context) => {
  const res = await fetch(
    `http://localhost:1337/api/articles?populate[0]=category&populate[1]=author&populate[2]=author.avatar`
  );
  const articles = await res.json();

  return { props: { articles } };
};

export default Home;
